### PR TITLE
solve path problem subscriptions

### PR DESCRIPTION
**Pull request by controlol**
This fixes download errors by escaping the custom download path. This caused problems with some paths that include characters that can not be used on the command line without escaping them. Therefore quotation marks should be added.

### CODE REVIEW

**Comment by Tzahi12345** [comment]
Hi! Sorry for the delayed response. Have you tested this by any chance? I can't remember if this was on Windows or Linux, but when I added quotes there was an issue where it was considered as part of the path (meaning if the intended target was `videos/<file name>.mp4` it ended up being `'videos/<file name>.mp4'`.

They look the same but in the latter case the folder had a quotation mark at the beginning and so did the file after the extension.

**Comment by GlassedSilver** [comment]
Wouldn't double quotation marks be universally correct?

afaik they work on any system. (Windows **and** UNIX/POSIX/UNIX-like)

**Comment by controlol** [comment]
You could give this an extra test on Windows, I tested it on Linux (container). But like GlassedSilver said, it should work universally.

**Comment by GlassedSilver** [comment]
ty for your contribution! You helped a lot and highlighted an issue in the backend that can be easily overlooked.

I'll merge this after the checks have passed and then hopefully nothing crashes and goes up in flames in the nightly release. :P 

Thank you again so very much!

**Pull request merged**
