### PR TITLE
Add download video button on player component.

### LINKED ISSUE #486: [BUG] Mp3 downloaded to the computer is only 200 Bytes.
**Firstly, thank the author for the devotion to YTDLM!!**

**Describe the bug**

Deployed the official docker image via the nightly branch. Launch logs look perfect without errors.

Then I randomly tried downloading some audio-only items. The downloading process on the server-side is pretty normal, and the audio downloaded could be played on the front UI.

But then I click download, the file I got is only around 200 Bytes.

Audio I tried (Any youtube link, no success): https://www.youtube.com/watch?v=Gx4JEBwVlXo

**Screenshots**

image
image
It indicates the file size is 282B.

**Environment**

Installed version: v4.2 - done  You are up to date.
Installation type: docker
Docker tag: nightly
Commit hash: 88cc8d0
Build date: 2021-10-01
browser: Chrome\edge latest stable.

### PR DESCRIPTION
**Pull request by chepe263**
Fix #486 #523

Added extra parameters to downloadFile function to prevent backend crashing.
Also, adds a new " download video" button because the current "floppy disk" button is unclear of it's purpose.

Needs re-compilation of front end.

### CODE REVIEW

**Comment by GlassedSilver** [comment]
Can you please look at the referenced issue and check out if this PR affects this, @chepe263?

Thank you so much!

**Comment by Tzahi12345** [comment]
Sorry I've been on a bit of a break! In October I merged #218 which was already a few years old and so some of the code got a bit mangled, including the download button. I can see how floppy disks are confusing in 2022...

@chepe263 Your code worked great! It did add some complexity and required an import of httpclient into player.component.ts.

Here's a quick comparison of the original implementation vs this PR (for those out of the loop):
* In this PR, we take the video/audio URL that we use to stream the content to *download* it instead with `this.http.get(url ...` ([see here](https://github.com/Tzahi12345/YoutubeDL-Material/pull/528/files#diff-f731da53131c50cd6faf9f0f37086d5333c4d683d89c32188be7b99ac6bba7d3R337)). Your browser will use the same mechanism it uses to stream the video to you to save it to disk instead.
* Originally, we used a custom API call /downloadFileFromServer that returned a blob (file, basically). In this approach, the server sends the file over the same way that Google Drive does when you click download there

Both give us the same result ultimately. Personally I prefer the second option because it loops into our existing API plumbing. The URL we generate to stream content from the server already feels like a whacky workaround so I'm a bit cautious about expanding on that.

In a PR I have up a [reverted some of the changes you made](https://github.com/Tzahi12345/YoutubeDL-Material/commit/df687263c52903893a9a97017ab411e56f3dca3b). I kept in the new icon -- I'm not great at UI design so I'll defer to you on that.

Let me know your thoughts!

**Comment by chepe263** [comment]
sorry for the hacky approach. It was the first time I had worked with angular and typescript. Your pr is really good, thank you for correcting my changes.

**Comment by GlassedSilver** [comment]
> sorry for the hacky approach. It was the first time I had worked with angular and typescript. Your pr is really good, thank you for correcting my changes.

No need to be sorry, you invested effort and tried to help, it’s much appreciated and you’re welcome to offer code at any time! :)

**Pull request merged**
