### PR TITLE
Docker ARMv7 hotfix

### PR DESCRIPTION
**Pull request by Tzahi12345**
Not to replace #890, simply to get things working until we figure out some last issues in the PR.

### CODE REVIEW

**Comment by martadinata666** [comment]
yep i encountered this issue, the armv7 needs to rebuild `pygithub` module that needs python3-dev and libffi-dev, but it making more complex than it should be . Should we just drop armv7?

**Comment by Tzahi12345** [comment]
Not sure, maybe I should make a poll or something.. don't wanna leave them in the dust but I'm not sure they make up a significant chunk of the user base.

Wonder if we can optionally include those libs if it's ARMv7. I'll play around with it, but I'll probably merge this in so I can get a release uploaded for v4.3.1..

**Comment by martadinata666** [comment]
Technically in my PR i replace the `gettwitchdownloader.py` to bash script like we fetch ffmpeg. So we don't need to rebuild something just to fetch something.

**Comment by Tzahi12345** [comment]
I do like that but just worried about cases where the latest release doesn't include the linux version of the CLI, I added some comments to your PR which has a particular version that doesn't have a linux release in it

**Comment by Tzahi12345** [comment]
Closing in favor of #899, I agree we should just remove armv7 support temporarily and try to get a script working that can look through multiple releases to find one with the appropriate asset

**Pull request closed without merging**
