### PR TITLE
Automated build & release via GitHub Actions

### PR DESCRIPTION
**Pull request by diveflo**
Hi,

as discussed in #257 this is a first draft for automatically building the app and creating (draft) releases for tagged commits.

### Building
Please forgive my ignorance here - web stuff was never my specialty :D So please have a look if the result looks as you would expect it and if e.g. the "prepare artifact upload" step makes sense like that. E.g. do the sub-folders change a lot? (-> we should not copy the sub-folders one by one but rather exclude others etc.)

It follows the basic steps as described in the `README.md` and then packages everything together so the result looks similar to previous releases here.
The build is triggered for any push to `master` or branches starting with `feat/`, tagged commits and pull requests.
The resulting archive is uploaded as a build artifact so it can be used in subsequent steps.

### Release
Again please let me know what your usual workflow here is.
I assumed a "standard" workflow: you tag a commit with a version identifier e.g. "v5.0", push it and create your release based on that version.
The "release" job in this workflow will trigger for any pushed tag following that naming convention and then:

- create a draft release with the name `YoutubeDL-Material {tag name}" and a "templated" body with "New features", "Minor additions" and "Bug fixes" headings
- download the build artifact from the previous job and repackage it as a zip file
- upload/attach that zip file to the release
- upload/attach the `docker-compose.yml` file to the release

You can (somewhat) see how it looks in my fork of your repo.

1. Pushed a tagged commit "v5.5": https://github.com/diveflo/YoutubeDL-Material/releases/tag/v5.5
2. This triggered this workflow: https://github.com/diveflo/YoutubeDL-Material/actions/runs/377411817 with a build and a release step
3. This created this draft release with the build output and the docker-compose file attached. (Sorry, I think draft releases can only be seen by the repo owner)
image

You could then "fill out" the actual release notes and publish the draft release.

Let me know what you think:)

### CODE REVIEW

**Comment by Tzahi12345** [comment]
Woah, I did not realize so much could be done with these workflows.

The way I usually release versions is by taking the source at the latest commit and doing what you did in the action. I then create a release, fill out the new improvements, and upload the zip/docker-compose.yml. So what you have here is *extremely* similar. I did notice one thing though, and that is the name of the uploaded zip file. I usually have the version appended to it so that if users download the app they know what version they have from the zip file name ([see here](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v4.1)). Not a big deal, but that is one discrepancy.

I think having a "whitelist"-type setup is ok regarding copying subfolders, those change rarely. In fact, there's only one place where I do have a subfolder for code and that's the `authentication` folder. It's a bit ugly, and the backend itself is well-deserving of a refactor which will probably lead to more subfolders popping up as the code gets more organized. Once that happens, this will probably break, so that's an argument for making it a "blacklist" instead. I'm a bit undecided here, but maybe it's worth excluding specific folders and letting the rest go through to prevent it from breaking in the future.

>The build is triggered for any push to master or branches starting with feat/, tagged commits and pull requests.
The resulting archive is uploaded as a build artifact so it can be used in subsequent steps.

A tiny bit confused on the purpose of this (besides the tagged commits), is it to make testing PR's easier? If so I'm all for it!

Overall, great stuff! Will definitely make my life easier. If you don't mind smoke testing the zip release you generated (I can't see it), I'd appreciate that, just to make sure the generated zip has no issues.

**Comment by diveflo** [comment]
>I did notice one thing though, and that is the name of the uploaded zip file. I usually have the version appended to it so that if users download the app they know what version they have from the zip file name ([see here](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v4.1)). Not a big deal, but that is one discrepancy.

Ah good catch - I'll add this (y)

> I think having a "whitelist"-type setup is ok regarding copying subfolders, those change rarely. In fact, there's only one place where I do have a subfolder for code and that's the `authentication` folder. It's a bit ugly, and the backend itself is well-deserving of a refactor which will probably lead to more subfolders popping up as the code gets more organized. Once that happens, this will probably break, so that's an argument for making it a "blacklist" instead. I'm a bit undecided here, but maybe it's worth excluding specific folders and letting the rest go through to prevent it from breaking in the future.

Then maybe let's go with YAGNI and keep it like this for now?

> > The build is triggered for any push to master or branches starting with feat/, tagged commits and pull requests.
> > The resulting archive is uploaded as a build artifact so it can be used in subsequent steps.
> 
> A tiny bit confused on the purpose of this (besides the tagged commits), is it to make testing PR's easier? If so I'm all for it!

Yeah basically as a "quality gate" - but here my ignorance for web stuff comes in again. Would the build steps (`npm install` & `ng build`) actually fail if I messed something up in my code?

> Overall, great stuff! Will definitely make my life easier. If you don't mind smoke testing the zip release you generated (I can't see it), I'd appreciate that, just to make sure the generated zip has no issues.

Is the pipeline triggered here not available to you? I'd actually expect you to be able to see this:
image

Anyway, here's the resulting zip:
[youtubedl-material.zip](https://github.com/Tzahi12345/YoutubeDL-Material/files/5582356/youtubedl-material.zip)

Looking at the diff, the build output is missing

- `appdata\encrypted.json`
- `public\assets\default.json`
- `users`

image

The users directory I just missed and will fix.
Do you have an idea why the first two files might be missing?

Thanks!

**Comment by Tzahi12345** [comment]
>Then maybe let's go with YAGNI and keep it like this for now?

That works!

>Yeah basically as a "quality gate" - but here my ignorance for web stuff comes in again. Would the build steps (npm install & ng build) actually fail if I messed something up in my code?

`ng build --prod` would fail if there was a compiler issue for the frontend, meaning a type, syntax, or any other error in the UI code that's detected at compile-time. Runtime issues won't be detected, but it does provide some kind of "smoke test" against merging code that won't even build.

>Do you have an idea why the first two files might be missing?

The `public/assets/default.json` is just for the development process, it allows us to have a local config without messing with the one in the `backend` folder. The `appdata/encrypted.json` was removed as encryption is now recommended to be done through a reverse proxy. Hope that clears that up!

Also, I just tested the zip, it looks good! So if you're good to merge I am too :)

**Comment by diveflo** [comment]
> `ng build --prod` would fail if there was a compiler issue for the frontend, meaning a type, syntax, or any other error in the UI code that's detected at compile-time. Runtime issues won't be detected, but it does provide some kind of "smoke test" against merging code that won't even build.

Thanks for the explanation:)

> Also, I just tested the zip, it looks good! So if you're good to merge I am too :)

Yup - I just rebased on master to linearize the history and cleaned up the commits a bit. If the builds run green I'd say let's merge it:)
Next time you create a release we can check that everything looks as expected!

Nice working with you:)

**Comment by Tzahi12345** [comment]
>Nice working with you:)

Ditto, thanks again for all the improvements!

**Comment by Tzahi12345** [comment]
Hm, I got this error when it tried the release job. Any thoughts?

```
Run Compress-Archive -Path /home/runner/work/_temp/youtubedl-material -DestinationPath youtubedl-material-refs/tags/v4.2.zip
  Compress-Archive -Path /home/runner/work/_temp/youtubedl-material -DestinationPath youtubedl-material-refs/tags/v4.2.zip
  shell: /usr/bin/pwsh -command ". '{0}'"
Compress-Archive: /home/runner/work/_temp/23ac08e5-0a8a-4949-bb6a-6f039c9c6caa.ps1:2
Line |
   2 |  Compress-Archive -Path /home/runner/work/_temp/youtubedl-material -De …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The path
     | '/home/runner/work/YoutubeDL-Material/YoutubeDL-Material/youtubedl-material-refs/tags' either does not exist or is not a valid file system path.
```

**Comment by diveflo** [comment]
Oh, yeah...my bad.
It's trying to put the complete git ref name (in this case `refs/tags/v4.2`) into the zip filename. Didn't think this through because the `create-release` action uses the same environment/context variable (`github.ref`) to produce the release name. But I just saw that they manually remove the `refs/tags/` portion of the context variable ([see here](https://github.com/actions/create-release/blob/main/src/create-release.js#L17))

So we have to do the same - I'll try to send you a pull request today or tomorrow:)

**Pull request merged**
