### PR TITLE
Better docker PR tests

### PR DESCRIPTION
**Pull request by Tzahi12345**
* Added docker build test for PRs using GH actions
* Made docker build and push variables on commit to master variable
* Fixed issue where subscription avatars would not appear in the sidebar
* Fixed issue where if you navigated away from a subscription, the UI would still check for updates to it

### CODE REVIEW

**Review by GlassedSilver — COMMENTED** [review]
lgtm, docker-pr.yml will still fail for PR checks of users other than you, but apart from that it's a go.

**Review by GlassedSilver — APPROVED** [review]

**Comment by Tzahi12345** [comment]
> lgtm, docker-pr.yml will still fail for PR checks of users other than you, but apart from that it's a go.

Because of the secrets? Maybe I should avoid having them there.

**Comment by GlassedSilver** [comment]
> > lgtm, docker-pr.yml will still fail for PR checks of users other than you, but apart from that it's a go.
> 
> Because of the secrets? Maybe I should avoid having them there.

yeah secrets don't work in workflows that fire as test for PRs automatically.

**Review by GlassedSilver — APPROVED** [review]
lgtm

**Pull request merged**
