### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by Tzahi12345**
Last minute cleanup before v4.3.1, I promise

### CODE REVIEW

**Comment by martadinata666** [comment]
Again about the twitch thing, arm64 will download x64 which is incorrect. I saw the release it doesn't have an arm64 release. 🤦🏼 We can rebuild, but is it worth the time?

**Comment by Tzahi12345** [comment]
Why would it? It does check if it's arm, which for arm64 would include the string "arm"

https://github.com/Tzahi12345/YoutubeDL-Material/blob/b859d08d86077a91de19a8a9c7130dfd3660c775/docker-utils/GetTwitchDownloader.py#LL12C30-L12C30

https://en.wikipedia.org/wiki/Uname

**Comment by martadinata666** [comment]
arm64 defined as aarch64 in python3, simply check with `print (machine)` in def `isARM` function.

Even if it is defined right, the release doesn't have aarch64/arm64 🤷🏼 
https://github.com/lay295/TwitchDownloader/releases/tag/1.52.5

**Comment by GlassedSilver** [comment]
Maybe we should raise an issue at the repo https://github.com/lay295/TwitchDownloader/, so the cause can be tackled at its root and similar projects don't all need to define custom logic all over again?

**Comment by martadinata666** [comment]
Yes this should be solved in upstream, I already create PR to make it also build for arm64, https://github.com/lay295/TwitchDownloader/pull/703. Still waiting for owner response, let see how it goes 🤞🏼

**Pull request merged**
