### PR TITLE
Added deleteAllFiles api endpoint

### PR DESCRIPTION
**Pull request by depuits**
Added an endpoint to remove all files base on the same search parameters as `api/getAllFiles`. This allows a user to periodically clean all files using a single api call. This is mostly useful when disabling the files manager.

### CODE REVIEW

**Comment by GlassedSilver** [comment]
Forgive me if I only checked this too superficially, but I see this got integrated into the public API, is this call protected by permissions or is it exposed without authentication on an instance that's protected?

I know that permissions have been worked into this project at a pretty late stage, and it's mostly targeted at personal use among trusted friends and family, but I want to make sure this kind of call doesn't start off with blatant trust towards everyone who has access to the API.

**Comment by GlassedSilver** [comment]
> [...]
> Are there any endpoints which are currently protected using an other method of authentication/authorization?

Not to my knowledge.

And yeah you do have a good point there. My thinking is that a moderator-role type of person wields a QUICK and easy weapon to nuke all contents rather than at least having to do some scripting.

IDK, usually I'd say I'd love to hear what Tzahi thinks, but he's been busy with life in recent times it seems so if it's okay for  you I'll leave this open for now. I doubt I'll do any breaking changes on my own here in case you consider running your own fork personally and want to fetch upstream patches without much fussing about.

Maybe I'm being too careful with this, but I'm always a bit wary of self-destruct buttons. :D

**Comment by depuits** [comment]
Leaving this currently open is fine for me. There are probably some other endpoints which might benefit from having some authentication so when something is provided for that I can look to change the function. A simplistic solution would be to create or add a key in the config which could be used as api secret?

**Comment by Tzahi12345** [comment]
Thanks for the PR! I'm not too concerned about the security risk because as you mentioned, someone can just call /api/getAllFiles and then /deleteFile. Have you validated this by any chance? I assume it works as it uses the same search logic as /api/getAllFiles  but I just want to make sure.

Ideally we can move the getAllFiles logic out of the request and then we could re-use it in both places but I won't make you do that. Unless you really want to :)

**Pull request merged**
