### PR TITLE
Fix entrypoint.sh

### PR DESCRIPTION
**Pull request by martadinata666**
* Revert https://github.com/Tzahi12345/YoutubeDL-Material/pull/864
Undetected due to maybe we don't play uid/gid so much, don't recurse, just find and change ownership
* Restore armv7 on nightly
* Regardless UID/GID do chown

### CODE REVIEW

**Comment by GlassedSilver** [comment]
In regard to the reversion, what is this helping?

**Comment by martadinata666** [comment]
in simple term `npm start && pm2 start` breaking the logic of args passing and skip entire chown process. This PR will make chown executed regardless condition, and removing args logic passing as we don't use it anyway. You can try current `nightly` tag by set uid/pid and it never change.

**Comment by Tzahi12345** [comment]
I'll be honest I don't know much about how linux permissions work, especially when it comes to Docker and this non-root setup we have. If you feel it's been tested enough to merge I'll go ahead and approve, otherwise if you have any resources for my learning (or anyone else) that you'd like to share, I'd appreciate it

**Comment by martadinata666** [comment]
This should be tested enough, im using this to set permission back and forth.
```

services:
  web:
    image: tzahi12345/youtubedl-material:nightly
    environment:
      ytdl_mongodb_connection_string: 'mongodb://db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
      UID: 1200
      GID: 2100
      PM2_HOME: /app/appdata
    volumes:
      - ./the-modified-entrypoint.sh:/app/entrypoint.sh
```
Then check folder into container, `docker exec the-container-name ls -aln` the number should match `UID/GID` on current `nightly` state in skipped all the login, and do `npm start` that is `UID/GID 1000`.

About permission things technically pretty simple, we change all `/app` to desired `UID/GID`, the problem is the script failed to do so. On #864 it add `pm2 start` that break checking condition. The #786 that weirdly doesn't work with `#!/bin/sh` maybe some formating differences.

**Comment by Tzahi12345** [comment]
LGTM, merging :) thanks for the explanation

**Review by Tzahi12345 — APPROVED** [review]

**Comment by samip5** [comment]
Unfortunately, it seems that his PR break real non-privileged container. gosu binary requires root, which when it doesn't have, fails miserably so the if statement should have been kept that check for root, and exec's directly if not uid 0.

**Comment by martadinata666** [comment]
Fortunately, you can override entrypoint to "npm start" to start the application and skip the permissions check entirely.

**Pull request merged**
