### PR TITLE
Add ability to request downloads using telegram

### PR DESCRIPTION
**Pull request by matthewfcarlson**
I find videos and want to easily send them for download. Since I already get notifications on my telegram channel, it would be awesome to poll it to check for messages that are just URLs and add them to the download queue

### CODE REVIEW

**Comment by Tzahi12345** [comment]
Sorry for the late response, but thanks for the PR!

I'm not the biggest fan of polling, I do like the hourly interval on tasks because perhaps some people want it, but that should be a separate PR. I say that because the Telegram bot API we use [supports webhooks](https://github.com/yagop/node-telegram-bot-api/blob/master/examples/webhook/express.js) so I think that's the best approach. It also allows us to expand the functionality later to support Discord/Slack.

Given that, I created #1031 which implements this functionality. The biggest challenge was considering what happens when you update the bot token or chat ID, so I made it so config_api broadcasts when config items are updated. I think that's a worthwhile upgrade which can be used in other areas as well (such as selecting a different youtube-dl fork).

With that said, I'll close the PR but I'd like to hear your thoughts on this. If polling has some use case that doesn't work with webhooks let me know and maybe we can explore this as well. Thanks again, I really appreciate it.

**Comment by matthewfcarlson** [comment]
I definitely think the webhook functionality is the way to go. In my particular use case, Youtube-DL is sitting as a docker container on my NAS and doesn't have a public address for Telegram to call the hook. That said, I think I could create some sort of relay system that passes the webhook through. Perhaps a setting to override the webhook URL in the config?

**Comment by matthewfcarlson** [comment]
Thanks for considering the request and for the thoughtful response!

**Comment by Tzahi12345** [comment]
Ah yeah I should've figured as I ran into this in my local dev environment. I used https://smee.io/ and overrode the URL which like you said, should be configurable.

One limitation is that it requires https access so smee.io solved that too.

**Comment by matthewfcarlson** [comment]
That's an awesome tool, I'm looking forward to the next release!

**Pull request closed without merging**
