### PR TITLE
Make more items translatable

### PR DESCRIPTION
**Pull request by UnlimitedCookies**
See title.

As you can see below, the close button is not translated. (The shown item is only one of the many improvements).
image

And I've also uniformed the close button.

### CODE REVIEW

**Comment by UnlimitedCookies** [comment]
I couldn't find `itemsPerPageLabel` anywhere except in the minified backend file. Also, the label for `of` doesn't seem to be changeable easily. Maybe you can elaborate on this, @Tzahi12345 .

**Comment by UnlimitedCookies** [comment]
I've done all I can do for now. :P I will add the German translations, for these newly added strings, at a later point.
Still, I couldn't do all the changes I would want (see comment above), because I am not that firm in developing JS currently.

Please test my changes and if all checks out, then I am looking forward to a merge :)

**Comment by Tzahi12345** [comment]
All looks good to me! I'll do some testing later tonight and get back to you. The missing translations was something I noticed recently, so I'm glad you addressed most of it. And nice job with the tooltips and UI improvements (tooltips and making the close button in the manage user dialog stroked).

I'm not sure what you mean regarding `itemsPerPageLabel`, I don't think I have that variable in the repo. Where did you see it?

For `permissionToLabel` problem, I know what you mean. This is an instance where a string is stored in TypeScript, so translating it becomes a *tiny* bit more complicated:

To make it properly translatable it needs to use the [Select ICU](https://angular.io/guide/i18n#translate-alternate-expressions). You can see where we do this (quite unelegantly) on line 326 of [settings.component.html](https://github.com/Tzahi12345/YoutubeDL-Material/blob/9cf4949c304e2559c1ae9fad557f93bf1d572adc/src/app/settings/settings.component.html)

```
<span i18n="Settings cancel and close button">{settingsAreTheSame + "", select, true {Close} false {Cancel} other {otha}}</span>`
```

The brackets are the important part here, encasing an "if statement" for the strings which is translatable.

If the settings have changed, the button will have the "Cancel" label, but if they haven't changed, it'll just say "Close". The `+ ""` after `settingsAreTheSame` is just to convert the boolean variable into a string, since the ICU select comparisons are string to string.

So how might we make `permissionToLabel` into an ICU expression? Here's the original:

```
<h3 matLine>{{permissionToLabel[permission] ? permissionToLabel[permission] : permission}}</h3>
```

In this instance, we're converting the permission key to its label (`file_manager` becomes `File manager`).  A complication in this instance is that we're already doing an "if statement", where we basically convert the permission to the string only if the conversion exists, otherwise we stick with the unconverted version (knowing what a [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) is will help here).

I don't know if this will work 100% (not on my main computer), but it would look something like this:

```
<h3 matLine *ngIf="permissionToLabel[permission]">{permission, select, file_manager {File manager} settings {Settings access} sharing {Share files} advanced_download {Use advanced download mode} downloads_manager {Downloads manager} other {TRANSLATION FAILED}</h3>

<h3 matLine *ngIf="!permissionToLabel">{{permission}}</h3>
```

The `*ngIf` is another way to do an if statement in HTML in Angular (if the expression is true, the div/span/h3/whatever will render).

You can take a stab at the ICU expressions if you'd like, but I know they're a bit complicated so don't feel bad if it doesn't make immediate sense. Otherwise I'll make sure they're in before the next update is mostly done.

Not sure if you've been doing this, but you can see the immediate changes of your UI updates by running `ng serve` in the root directory (you need Angular installed). Then you can run `node app.js` in the `backend` directory, but before doing so you also need to set the env var `YTDL_MODE` to `debug`. Navigate to `localhost:4200` and your dev instance will be up and running!

Sorry for the huge wall of text (might add some of this to the wiki), but I hope some of the dynamic string translation weirdness makes more sense. Shoot any questions over, I'll be happy to answer.

**Comment by Tzahi12345** [comment]
Just tested it out, all looks good. Thanks for the PR!

Merging...

**Pull request merged**
