### PR TITLE
fix: #682 install tzdata

### PR DESCRIPTION
**Pull request by adripo**

### CODE REVIEW

**Comment by Tzahi12345** [comment]
Can you add a quick description explaining the benefit of adding tzdata?

**Comment by martadinata666** [comment]
Set timezone for the app, technically there is two way to set time in container, mount the `/etc/localtime` or use install `tzdata` and user just passing the region to TZ env like `UTC`, `Asia/Bangkok`

**Comment by adripo** [comment]
Also `DEBIAN_FRONTEND=noninteractive` should be ARG, not ENV because it is used only in the build process.

**Review by GlassedSilver — APPROVED** [review]
lgtm!

**Pull request merged**
