### PR TITLE
Clean up docker image

### PR DESCRIPTION
**Pull request by dejan995**
Added some commands to clean up the image after apt-get does its thing.
It should shave off a couple of megabytes, nothing to big though.

### CODE REVIEW

**Review by GlassedSilver — COMMENTED** [review]
Thank you!

**Comment by GlassedSilver** [comment]
Any reason why we use apt instead of apt-get at the end of the file though?

**Comment by dejan995** [comment]
> Any reason why we use apt instead of apt-get at the end of the file though?

They are basicly the same.
Here is some info from the Ubuntu forums:

> apt-get may be considered as lower-level and "back-end", and support other APT-based tools. apt is designed for end-users (human) and its output may be changed between versions. Note from apt(8): The `apt` command is meant to be pleasant for end users and does not need to be backward compatible like apt-get(8)

I use apt in my images. The commands I added are just copy paste because they are generic, but feel free to add the -get part, it won't break anything.

**Comment by GlassedSilver** [comment]
I know about the difference, I was just wondering if there was a specific reason we may use it. If not then I‘ll feel free to adapt that once the build passes and we got the other current issues sorted out for consistency. :)

**Pull request merged**
